# conf/config.yaml
defaults:
  - _self_

scraping:
  #url: "https://pricecheck.uk.com/beauty"
  url: "https://pricecheck.uk.com/brands/2025"
  output_file: "product_details.csv"
  wait_time: 10  # Example value in seconds
